FROM openjdk:8-alpine

COPY ./shop-product/build/libs/shop-product-0.0.1-SNAPSHOT.jar /app/shop-product-0.0.1-SNAPSHOT.jar

COMMAND ["java", "-jar", "shop-product-0.0.1-SNAPSHOT.jar"]

EXPOSE 8080
