def DOCKER_IMAGE_NAME = "192.168.219.104:5000/product"
def NAMEPSACE = "product"
def VERSION = "${env.BUILD_NUMBER}"
def DATE = new Date();

podTemplate(label: 'builder',
	containers: [
		containerTemplate(
			name: 'docker',
			image: 'docker',
			command: 'cat',
			alwaysPullImage: false,
			ttyEnabled: true
		)
]) {
	node('builder') {
		stage('Checkout') {
			checkout scm
		}

		stage('Build') {
			container('docker') {
				sh "./shop-product/gradlew build"
			}
		}

		stage('Docker build') {
			container('docker') {
				sh "docker build -t ${DOCKER_IMAGE_NAME} ."
				sh "docker push ${DOCKER_IMAGE_NAME}"
			}
		}
	}
}