def DOCKER_IMAGE_NAME = "192.168.219.104:5000/product"
def NAMEPSACE = "product"
def VERSION = "${env.BUILD_NUMBER}"
def DATE = new Date();

pordTemplate(label: 'builder',
	containers: [
		containerTemplate(
			name: 'gradle',
			image: 'gradle:5.6-jdk8',
			command: 'cat',
			ttyEnabled: true
		),
		containerTemplate(
			name: 'docker',
			image: 'docker',
			command: 'cat',
			ttyEnabled: true
		),
		containerTemplate(
			name: 'kubectl',
			image: 'lachlanevenson/k8s-kubectl:v1.15.3',
			command: 'cat',
			ttyEnabled: true
		)
]) {
	node('builder') {
		stage('Checkout') {
			checkout scm
		}

		stage('Build') {
			container('gradle') {
				sh "gradle -x test build"
			}
		}

		stage('Docker build') {
			container('docker') {
				sh "docker build -t ${DOCKER_IMAGE_NAME} ."
				sh "docker push ${DOCKER_IMAGE_NAME}"
			}
		}

		stage('Run kubectl') {
			container('kubectl') {
				sh "kubectl get ns ${NAMEPSACE} || kubectl create ns ${NAMEPSACE}"

				sh "echo ${DATE}"
				sh "sed -i.bak 's#DATE_STRING#${DATE}#'" ./k8s/product.yaml

				sh "kubectl apply -f ./k8s/product.yaml -n ${NAMEPSACE}"
			}
		}
	}
}