apiVersion: v1
kind: Namespace
metadata:
  name: product

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  namespace: product
  labels:
    app: product
spec:
    replicas: 3
    selector:
      matchLabels:
        app: product
    template:
      metadata:
        labels:
          app: product
      spec:
        containers:
        - name: product
          image: 192.168.219.104:5000/product
          imagePullPolicy: Always
          env:
          - name: DATE
            value: 'DATE_STRING'
          ports:
          - containerPort: 8080
        tolerations:
        - key: "app"
          value: "api"
          effect: "NoSchedule"

---

apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: product
spec:
  type: NodePort
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
